"""initial schema — all 7 tables from the original spec

Revision ID: 0001
Revises:
Create Date: 2026-09-13

Hand-written rather than generated by `alembic revision --autogenerate`
— this sandbox has no database to autogenerate against. Every column,
type, nullability, default, and foreign key below was cross-checked
against the actual SQLAlchemy models in app/models/ line by line
(documented in the Phase 20 report) rather than retyped from memory.
Tables are created in dependency order: users and problems first (no
foreign keys out), then everything that references them, then
ai_reviews last (the only table that references submissions).
"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=False, unique=True),
        sa.Column("password_hash", sa.String(255), nullable=False),
        sa.Column("role", sa.String(20), nullable=False, server_default="student"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_users_email", "users", ["email"])

    op.create_table(
        "problems",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("difficulty", sa.String(20), nullable=False),
        sa.Column("topic", sa.String(50), nullable=False),
        sa.Column("constraints", sa.JSON, nullable=True),
        sa.Column("expected_input", sa.Text, nullable=True),
        sa.Column("expected_output", sa.Text, nullable=True),
        sa.Column("examples", sa.JSON, nullable=True),
        sa.Column("hints", sa.JSON, nullable=True),
        sa.Column("starter_code", sa.JSON, nullable=True),
        sa.Column("estimated_time", sa.String(20), nullable=True),
        sa.Column("ai_recommended", sa.Boolean, nullable=False, server_default=sa.false()),
    )

    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("problem_id", sa.Integer, sa.ForeignKey("problems.id"), nullable=False),
        sa.Column("input", sa.Text, nullable=False),
        sa.Column("expected_output", sa.Text, nullable=False),
        sa.Column("hidden", sa.Boolean, nullable=False, server_default=sa.true()),
    )

    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("problem_id", sa.Integer, sa.ForeignKey("problems.id"), nullable=False),
        sa.Column("code", sa.Text, nullable=False),
        sa.Column("language", sa.String(20), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("runtime", sa.Float, nullable=True),
        sa.Column("memory", sa.Float, nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("solving_time", sa.Integer, nullable=True),
        sa.Column("attempt_number", sa.Integer, nullable=False, server_default="1"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )

    op.create_table(
        "progress",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), primary_key=True),
        sa.Column("solved_count", sa.Integer, nullable=False, server_default="0"),
        sa.Column("accuracy", sa.Float, nullable=False, server_default="0"),
        sa.Column("streak", sa.Integer, nullable=False, server_default="0"),
        sa.Column("average_solve_time", sa.Float, nullable=True),
        sa.Column("topic_metrics", sa.JSON, nullable=True),
    )

    op.create_table(
        "user_problem_stats",
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), primary_key=True),
        sa.Column("problem_id", sa.Integer, sa.ForeignKey("problems.id"), primary_key=True),
        sa.Column("attempts", sa.Integer, nullable=False, server_default="0"),
        sa.Column("best_time_seconds", sa.Integer, nullable=True),
        sa.Column("solved", sa.Boolean, nullable=False, server_default=sa.false()),
    )

    op.create_table(
        "ai_reviews",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("submission_id", sa.Integer, sa.ForeignKey("submissions.id"), nullable=False, unique=True),
        sa.Column("correctness", sa.Text, nullable=True),
        sa.Column("complexity", sa.Text, nullable=True),
        sa.Column("code_quality", sa.Text, nullable=True),
        sa.Column("feedback", sa.Text, nullable=True),
        sa.Column("suggestions", sa.Text, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )


def downgrade() -> None:
    # Reverse dependency order.
    op.drop_table("ai_reviews")
    op.drop_table("user_problem_stats")
    op.drop_table("progress")
    op.drop_table("submissions")
    op.drop_table("test_cases")
    op.drop_table("problems")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
